#!/bin/bash

# A shell script that dereferences a person's orcid ID and extracts the turtle info. It places
# that info in a ~/.sc directory in a file called config.ttl and then adds the username and host
# information to that file, in turtle also.
# an example orcid ID is 0000-0003-4091-6059

orcid_id=$1

#define file locations

sc_dir=~/.sc
sc_config="config.ttl"
sc_file=$sc_dir"/"$sc_config

echo "Smart container tutle directory: " $sc_dir
echo "Smart container tutle file name: " $sc_config
echo "File to write smart container information to: " $sc_file

if [ "$orcid_id" == "" ]; then
    echo "USAGE: sc_info orcid_id"
    exit 1
fi

# make directory ~/.sc if it does not exist

mkdir -p $sc_dir

if [ -f $sc_file ]
then
    rm $sc_file
fi

curl --header "Accept: text/turtle" -L http://orcid.org/$orcid_id > $sc_file

me="$(whoami)"
hostname="$(hostname)"

fqn=$(host -TtA $(hostname -s)|grep "has address"|awk '{print $1}') ;
if [[ "${fqn}" == "" ]] ; then fqn=$(hostname -s) ; fi ;

echo "Whoami: " $me
echo "Hostname: " $fqn

sed -e 's/HOST_NAME/'$fqn'/g' turtle-template.ttl > host.ttl
sed -e 's/WHOAMI/'$me'/g' host.ttl > host_and_me.ttl
rm host.ttl
cat host_and_me.ttl >> $sc_file
rm host_and_me.ttl